-- =====================================================================
--  ALREADY APPLIED — 2026-09-29. Kept as the record of what was run and
--  why. Nothing in this file needs running again. The remaining storage
--  step is 03_storage_update_policy.sql.
--
--  WHAT WAS WRONG
--  Anyone holding the public anon key (it ships in the browser bundle of
--  every page — it is meant to be public) could list and download the
--  proof-of-age documents. Verified against production before the fix:
--
--    POST /storage/v1/object/list/proof-of-age   -> 200, 62 folders
--    GET  /storage/v1/object/proof-of-age/<path> -> 200, 74,265 bytes
--
--  Those are photographs of minors' identity documents.
--
--  The BUCKET setting was never the problem — proof-of-age has
--  public = false. It was two SELECT policies on storage.objects, a table
--  SUPABASE_MIGRATION.sql never touches, which is why the leak outlived
--  every migration run.
--
--  WHAT WAS ACTUALLY RUN
--  Not the enumerate-and-drop DO block this file used to contain. That
--  needed ownership of storage.objects, which belongs to
--  supabase_storage_admin; the SQL editor connects as `postgres`, which on
--  this project is NOT a member of that role, so both `ALTER TABLE` and
--  `SET LOCAL ROLE supabase_storage_admin` were refused with 42501.
--  Plain DROP POLICY as postgres was accepted. These two statements ran:
--
--    DROP POLICY "Allow public/anon uploads s6hol4_0" ON storage.objects;
--    DROP POLICY "Allow public read access"           ON storage.objects;
--
--  Both, not one: RLS is permissive-OR, so any single remaining policy
--  would have kept the leak open on its own.
--
--    "Allow public/anon uploads s6hol4_0" was SELECT to {anon,authenticated}
--    with qual `true` — read access to every object in every bucket, in
--    spite of the word "uploads" in its name.
--
--    "Allow public read access" was SELECT to {public} on team-logos,
--    consent-forms, proof-of-age and receipts. {public} in pg_policies
--    means ALL roles, anon included — not "the public buckets".
--
--  "Only admin can read proof-of-age" was LEFT IN PLACE. It is inert: it
--  tests auth.jwt()->>'role' = 'admin', the anon key's JWT carries
--  "role":"anon", and admin auth in this app is a signed cookie rather
--  than a Supabase JWT. It grants nobody anything.
--
--  VERIFIED AFTER (all cache-busted — a Supabase CDN hit on an object
--  fetched during the pre-fix probe returned a stale 200 and briefly
--  looked like the leak was still open):
--
--    anon LIST, all four buckets                    -> 0 rows
--    anon GET, 5 distinct proof-of-age objects      -> 400, cache=BYPASS
--    no key at all, and /object/public/proof-of-age -> 400
--    anon upload, team-logos/player-photos/proof-of-age -> 200
--    public buckets via /object/public/...          -> 200, bytes intact
--
--  WHY REMOVING READ ACCESS WAS SAFE
--  Every storage call in the app was enumerated first:
--
--    anon (browser)  lib/api/registration.ts:388  .upload()       WRITE
--                    lib/api/registration.ts:412  .getPublicUrl() no network,
--                                                 it only builds a string
--
--    service_role    app/api/team/upload/route.ts
--    (server only,   app/api/team/add-player/route.ts
--     bypasses RLS   app/api/team/document-url/route.ts
--     entirely, so   app/api/admin/get-receipt-signed-url/route.ts
--     no policy      app/api/admin/resolve-change/route.ts
--     affects it)    lib/team-data.ts
--
--  The three public buckets are still readable by the whole internet
--  through /object/public/... — that path checks the bucket flag only and
--  never consults RLS. What the browser lost is the ability to LIST them,
--  which it never used and which was quietly exposing a directory of
--  every player photo and receipt in the system.
--
--  STILL OUTSTANDING, and visible in the policy list below:
--  six redundant INSERT policies. Three are identical `true` grants to
--  {anon,authenticated} — i.e. insert into any bucket — and two more
--  duplicate each other on proof-of-age. Two of them name `consent-forms`
--  and `receipts`, buckets that no longer exist. They are not a read
--  leak, so they were left alone rather than risk breaking the venue
--  upload path on the same day as the fix. Collapsing them into one
--  scoped INSERT policy is the tidy-up.
-- =====================================================================

SELECT policyname, cmd, roles, qual, with_check
FROM pg_policies
WHERE schemaname = 'storage' AND tablename = 'objects'
ORDER BY cmd, policyname;
